### ISSUE TITLE
exception when testing a 4x4 matrix

### ISSUE THREAD

**Issue by gocanal** [JingenXiang/MatrixInversion#5]
Hello,
I use MakeData to create a small 4x4 matrix and ran into exception (using the provided Inverse.jar) with command:
    hadoop jar Inverse.jar matrix.Inverse 2 2

java.lang.ArrayIndexOutOfBoundsException: 6
at matrix.LUInverse$LUInverse_Reducer.read_Li(LUInverse.java:326)
at matrix.LUInverse$LUInverse_Reducer.reduce(LUInverse.java:347)
at matrix.LUInverse$LUInverse_Reducer.reduce(LUInverse.java:169)

Looking at the code, it seems that it is because the array Li has a length of 6 (so index is 0 ~ 5) but index l has value of 6.

Is there a minimum matrix order supported ?
thanks

**Comment by gocanal** [comment]
Managed to make it work with different number of reducers:
limit set to 2, reducer set to 4.

**Comment by catadiel** [comment]
Hi gocanal,
I'm working with this program and I've got the same issue.
How have you solved?
